import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import Header from "@/widgets/Header";
import Footer from "@/widgets/Footer";
import { ReduxProvider } from "@/state/Providers";
import { SessionProvider } from 'next-auth/react';
import "./_styles/globals.scss";
import "./_styles/normalize.css";


const geistSans = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const geistMono = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <SessionProvider>
         <ReduxProvider>
           <Header />
           {children}
           <Footer />
         </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
